@username = mnmn
@email = mnmn@gmail.com
@password = mnmn123

### For Registering User
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}


### For Login
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


### Accessing Protected Data
GET http://127.0.0.1:8000/protected/
Authorization: Bearer {{access_token}}

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MTQyMDMzMCwiaWF0IjoxNzUxMzMzOTMwLCJqdGkiOiJmZTYyNmM1MmNhNzk0MzNiYjcwMjRlMWIyMjU5ZDFlYyIsInVzZXJfaWQiOjIyfQ.l4Cv3lWJyrGe3NXtQxh-y2EMlqvu5-aR42_yD1HO6sU

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM0MjMwLCJpYXQiOjE3NTEzMzM5MzAsImp0aSI6IjM3NWQwMzc2MmQzYjQ1N2JhM2U1M2VjMmNhZmRkOGI0IiwidXNlcl9pZCI6MjJ9.bCusMcdOP_gZdRXoVfHYHzwMc_UWNoLuTt-EGp2U0Qk



### Logout
POST http://127.0.0.1:8000/logout/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh": "{{refresh_token}}"
}


### For Refresh Token
POST http://127.0.0.1:8000/refresh/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh": "{{refresh_token}}"
}
